CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(254) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100),
    last_name VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,

    CONSTRAINT email_len_chk CHECK (length(email) BETWEEN 3 AND 254)
);

CREATE UNIQUE INDEX ux_users_email_lower ON users (lower(email));
