CREATE TABLE IF NOT EXISTS transfers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_account_id BIGINT NOT NULL,
    to_account_id BIGINT NOT NULL,
    amount NUMERIC(19, 4) NOT NULL,
    currency CHAR(3) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    description VARCHAR(255),
    initiated_by BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT now(),
    CONSTRAINT transfers_amount_chk CHECK (amount > 0),
    CONSTRAINT transfers_from_to_chk CHECK (from_account_id <> to_account_id),
    CONSTRAINT transfers_currency_chk CHECK (char_length(currency) = 3),
    CONSTRAINT transfers_status_chk CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED')),
    CONSTRAINT transfers_from_fk FOREIGN KEY (from_account_id) REFERENCES accounts(id) ON UPDATE CASCADE,
    CONSTRAINT transfers_to_fk FOREIGN KEY (to_account_id) REFERENCES accounts(id) ON UPDATE CASCADE,
    CONSTRAINT transfers_initiated_by_fk FOREIGN KEY (initiated_by) REFERENCES users(id) ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_transfers_from_account ON transfers(from_account_id);
CREATE INDEX IF NOT EXISTS ix_transfers_to_account ON transfers(to_account_id);
CREATE INDEX IF NOT EXISTS ix_transfers_initiated_by ON transfers(initiated_by);
CREATE INDEX IF NOT EXISTS ix_transfers_created_at ON transfers(created_at);
CREATE INDEX IF NOT EXISTS ix_transfers_status ON transfers(status);
