CREATE TABLE accounts (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     owner_id BIGINT NOT NULL,
     currency CHAR(3) NOT NULL,
     alias VARCHAR(100),
     balance NUMERIC(19, 4) NOT NULL DEFAULT 0,
     is_active BOOLEAN NOT NULL DEFAULT TRUE,
     created_at TIMESTAMP NOT NULL DEFAULT now(),

     CONSTRAINT accounts_currency_chk CHECK (char_length(currency) = 3),

     CONSTRAINT accounts_owner_fk
         FOREIGN KEY (owner_id)
             REFERENCES auth.users(id)
             ON UPDATE CASCADE
             ON DELETE CASCADE
);

CREATE INDEX ix_accounts_owner ON accounts(owner_id);
